clang 6 requires deprecation attribute in front
Fixes errors like:
```
../include/aspect/simulator_access.h:762:35: error: 'deprecated'
attribute cannot be applied to types
      find_postprocessor () const DEAL_II_DEPRECATED;
```